import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Button, Container, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Pickaxe</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/img/logo.png" />
            </Head>
            <Container sx={{ marginTop: "26px" }}>
                <Image
                    src={"/img/navLogo.png"}
                    alt={"pickaxe_logo"}
                    width={144}
                    height={32}
                />
            </Container>
            <Container>
                <Typography>Pickaxe is under construction</Typography>
                <Typography
                    sx={{
                        fontFamily: "Open Sans",
                        fontSize: "24px",
                        lineHeight: "30px",
                    }}
                >
                    But the beta version is open to anyone who asks. It's free
                    and (semi)-ready to be tested!
                </Typography>
                <Button
                    sx={{
                        fontWeight: "800",
                        textTransform: "unset",
                    }}
                >
                    Visit beta
                </Button>
            </Container>
        </>
    );
}
